#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-poetry_core
Version  : 1.0.8
Release  : 6
URL      : https://files.pythonhosted.org/packages/51/be/c4dce945cf7de2dc38d94cf724525f2a97d83b18403eeeb87eecb715dada/poetry-core-1.0.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/51/be/c4dce945cf7de2dc38d94cf724525f2a97d83b18403eeeb87eecb715dada/poetry-core-1.0.8.tar.gz
Summary  : Poetry PEP 517 Build Backend
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause MIT
Requires: pypi-poetry_core-license = %{version}-%{release}
Requires: pypi-poetry_core-python = %{version}-%{release}
Requires: pypi-poetry_core-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Poetry Core
[![PyPI version](https://img.shields.io/pypi/v/poetry-core)](https://pypi.org/project/poetry-core/)
[![Python Versions](https://img.shields.io/pypi/pyversions/poetry-core)](https://pypi.org/project/poetry-core/)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
[![](https://github.com/python-poetry/poetry-core/workflows/Tests/badge.svg)](https://github.com/python-poetry/poetry-core/actions?query=workflow%3ATests)

%package license
Summary: license components for the pypi-poetry_core package.
Group: Default

%description license
license components for the pypi-poetry_core package.


%package python
Summary: python components for the pypi-poetry_core package.
Group: Default
Requires: pypi-poetry_core-python3 = %{version}-%{release}

%description python
python components for the pypi-poetry_core package.


%package python3
Summary: python3 components for the pypi-poetry_core package.
Group: Default
Requires: python3-core
Provides: pypi(poetry_core)

%description python3
python3 components for the pypi-poetry_core package.


%prep
%setup -q -n poetry-core-1.0.8
cd %{_builddir}/poetry-core-1.0.8
pushd ..
cp -a poetry-core-1.0.8 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656394904
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-poetry_core
cp %{_builddir}/poetry-core-1.0.8/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/c6ffa3c5b833378b2a51577528914515f7f21934
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/attrs.LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/d7a2c5aa77742bd20bb82eeb0a8a5362d32cc2f4
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/jsonschema/COPYING %{buildroot}/usr/share/package-licenses/pypi-poetry_core/b1e6ce156efc7a88b6326c47b15f50ff3c3dfb10
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/jsonschema/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/efd3a84c29d6331c1ef6a2b6d7694928d097bcc5
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/lark-parser.LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/5c3d9041204d05ab9f5bf721a4ddb60b583b10e2
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/packaging/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/bd0b945d001aebc12dd7cdbf100427f1bc8d6957
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/packaging/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-poetry_core/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/pyparsing.LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/pyrsistent/LICENSE.mit %{buildroot}/usr/share/package-licenses/pypi-poetry_core/51fb67a89c327cbfaab8524db9f68819533b2c98
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/six.LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/5aa89b53a6e35810f63b69d01b463ef3c6576853
cp %{_builddir}/poetry-core-1.0.8/poetry/core/_vendor/tomlkit/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/0a2a6bdf2331975afa1b884149d86b521ce0f3f9
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-poetry_core/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
/usr/share/package-licenses/pypi-poetry_core/0a2a6bdf2331975afa1b884149d86b521ce0f3f9
/usr/share/package-licenses/pypi-poetry_core/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
/usr/share/package-licenses/pypi-poetry_core/51fb67a89c327cbfaab8524db9f68819533b2c98
/usr/share/package-licenses/pypi-poetry_core/5aa89b53a6e35810f63b69d01b463ef3c6576853
/usr/share/package-licenses/pypi-poetry_core/5c3d9041204d05ab9f5bf721a4ddb60b583b10e2
/usr/share/package-licenses/pypi-poetry_core/b1e6ce156efc7a88b6326c47b15f50ff3c3dfb10
/usr/share/package-licenses/pypi-poetry_core/bd0b945d001aebc12dd7cdbf100427f1bc8d6957
/usr/share/package-licenses/pypi-poetry_core/c6ffa3c5b833378b2a51577528914515f7f21934
/usr/share/package-licenses/pypi-poetry_core/d7a2c5aa77742bd20bb82eeb0a8a5362d32cc2f4
/usr/share/package-licenses/pypi-poetry_core/efd3a84c29d6331c1ef6a2b6d7694928d097bcc5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
