#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v22
# autospec commit: 247c192
#
Name     : pypi-poetry_core
Version  : 2.1.2
Release  : 37
URL      : https://files.pythonhosted.org/packages/84/2a/572c141e2a15b933b4a49eb888b0ae7335604f57c0f91a7298ae56d2df7c/poetry_core-2.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/84/2a/572c141e2a15b933b4a49eb888b0ae7335604f57c0f91a7298ae56d2df7c/poetry_core-2.1.2.tar.gz
Summary  : Poetry PEP 517 Build Backend
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause MIT
Requires: pypi-poetry_core-license = %{version}-%{release}
Requires: pypi-poetry_core-python = %{version}-%{release}
Requires: pypi-poetry_core-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Poetry Core
[![Poetry](https://img.shields.io/endpoint?url=https://python-poetry.org/badge/v0.json)](https://python-poetry.org/)
[![PyPI version](https://img.shields.io/pypi/v/poetry-core)](https://pypi.org/project/poetry-core/)
[![Python Versions](https://img.shields.io/pypi/pyversions/poetry-core)](https://pypi.org/project/poetry-core/)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
[![](https://github.com/python-poetry/poetry-core/workflows/Tests/badge.svg)](https://github.com/python-poetry/poetry-core/actions?query=workflow%3ATests)

%package license
Summary: license components for the pypi-poetry_core package.
Group: Default

%description license
license components for the pypi-poetry_core package.


%package python
Summary: python components for the pypi-poetry_core package.
Group: Default
Requires: pypi-poetry_core-python3 = %{version}-%{release}

%description python
python components for the pypi-poetry_core package.


%package python3
Summary: python3 components for the pypi-poetry_core package.
Group: Default
Requires: python3-core
Provides: pypi(poetry_core)

%description python3
python3 components for the pypi-poetry_core package.


%prep
%setup -q -n poetry_core-2.1.2
cd %{_builddir}/poetry_core-2.1.2
pushd ..
cp -a poetry_core-2.1.2 buildavx2
popd
pushd ..
cp -a poetry_core-2.1.2 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743429605
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd
pushd ../buildapx/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-poetry_core
cp %{_builddir}/poetry_core-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/aa1d60525fded9648cab0e59a4338652671ad600 || :
cp %{_builddir}/poetry_core-%{version}/src/poetry/core/_vendor/fastjsonschema/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/b15833fac355dbd5f534e0cbc928a2ca38f7d551 || :
cp %{_builddir}/poetry_core-%{version}/src/poetry/core/_vendor/lark/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/9addd8ed1823a0daf664e416466ddad2466ee40f || :
cp %{_builddir}/poetry_core-%{version}/src/poetry/core/_vendor/packaging/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/poetry_core-%{version}/src/poetry/core/_vendor/packaging/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-poetry_core/fdc0e4eabc45522b079deff7d03d70528d775dc0 || :
cp %{_builddir}/poetry_core-%{version}/src/poetry/core/_vendor/tomli/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/9da6ca26337a886fb3e8d30efd4aeda623dc9ade || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/case_sensitive_exclusions/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/complete/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/complete_dynamic/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/complete_new/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/default_src_with_excluded_data/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/default_with_excluded_data/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/default_with_excluded_data_toml/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/exclude_nested_data_toml/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/invalid_case_sensitive_exclusions/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/licenses_and_copying/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
cp %{_builddir}/poetry_core-%{version}/tests/masonry/builders/fixtures/with-include/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
pushd ../buildapx/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-va dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-poetry_core/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-poetry_core/84661790a5df00ab944c2d37978d6ce5ac88e554
/usr/share/package-licenses/pypi-poetry_core/9addd8ed1823a0daf664e416466ddad2466ee40f
/usr/share/package-licenses/pypi-poetry_core/9da6ca26337a886fb3e8d30efd4aeda623dc9ade
/usr/share/package-licenses/pypi-poetry_core/aa1d60525fded9648cab0e59a4338652671ad600
/usr/share/package-licenses/pypi-poetry_core/b15833fac355dbd5f534e0cbc928a2ca38f7d551
/usr/share/package-licenses/pypi-poetry_core/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
